steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gateway'
      - '-t'
      - 'us-central1-docker.pkg.dev/ahmet-personal-api/krew-review-agent/gateway:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/ahmet-personal-api/krew-review-agent/gateway:latest'
